[package]
name = "paracon-node"
version = "0.1.0"
authors = ["Paracon"]
build = "build.rs"
edition = "2018"

[package.metadata.docs.rs]
targets = ["x86_64-unknown-linux-gnu"]

[dependencies]
futures = "0.3.4"
log = "0.4.8"
structopt = "0.3.8"
jsonrpc-core = "14.0.5"
hex-literal = "0.2.1"

paracon-runtime = { version = "0.1.0", path = "../runtime" }
pallet-contracts-rpc = "0.8.0-alpha.6"

sc-basic-authorship = "0.8.0-alpha.6"
sc-cli = "0.8.0-alpha.6"
sc-client = "0.8.0-alpha.6"
sc-client-api = "2.0.0-alpha.6"
sc-consensus-aura = "0.8.0-alpha.6"
sc-executor = "0.8.0-alpha.6"
sc-finality-grandpa = "0.8.0-alpha.6"
sc-network = "0.8.0-alpha.6"
sc-rpc = "2.0.0-alpha.6"
sc-service = "0.8.0-alpha.6"
sc-transaction-pool = "2.0.0-alpha.6"
sp-consensus = "0.8.0-alpha.6"
sp-consensus-aura = "0.8.0-alpha.6"
sp-core = "2.0.0-alpha.6"
sp-finality-grandpa = "2.0.0-alpha.6"
sp-inherents = "2.0.0-alpha.6"
sp-runtime = "2.0.0-alpha.6"
sp-transaction-pool = "2.0.0-alpha.6"

[build-dependencies]
substrate-build-script-utils = "2.0.0-alpha.6"

[[bin]]
name = "paracon"
path = "src/main.rs"
